# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ProductHunt Daily Digest RSS
email: freeatnet+phddrss@freeatnet.com
description: A blog that publishes top 10 tech products published to ProductHunt, daily.
baseurl: "/producthunt-digest-rss" # the subpath of your site, e.g. /blog
url: "http://freeatnet.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

gems:
  - jekyll-feed

# Build settings
markdown_ext: markdown,md
markdown: kramdown
